// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoClient interface {
	GlobalCounter(ctx context.Context, in *CounterParam, opts ...grpc.CallOption) (Echo_GlobalCounterClient, error)
}

type echoClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoClient(cc grpc.ClientConnInterface) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) GlobalCounter(ctx context.Context, in *CounterParam, opts ...grpc.CallOption) (Echo_GlobalCounterClient, error) {
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[0], "/echo.Echo/GlobalCounter", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoGlobalCounterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Echo_GlobalCounterClient interface {
	Recv() (*GlobalCounterResponse, error)
	grpc.ClientStream
}

type echoGlobalCounterClient struct {
	grpc.ClientStream
}

func (x *echoGlobalCounterClient) Recv() (*GlobalCounterResponse, error) {
	m := new(GlobalCounterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EchoServer is the server API for Echo service.
// All implementations must embed UnimplementedEchoServer
// for forward compatibility
type EchoServer interface {
	GlobalCounter(*CounterParam, Echo_GlobalCounterServer) error
	mustEmbedUnimplementedEchoServer()
}

// UnimplementedEchoServer must be embedded to have forward compatible implementations.
type UnimplementedEchoServer struct {
}

func (UnimplementedEchoServer) GlobalCounter(*CounterParam, Echo_GlobalCounterServer) error {
	return status.Errorf(codes.Unimplemented, "method GlobalCounter not implemented")
}
func (UnimplementedEchoServer) mustEmbedUnimplementedEchoServer() {}

// UnsafeEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServer will
// result in compilation errors.
type UnsafeEchoServer interface {
	mustEmbedUnimplementedEchoServer()
}

func RegisterEchoServer(s grpc.ServiceRegistrar, srv EchoServer) {
	s.RegisterService(&Echo_ServiceDesc, srv)
}

func _Echo_GlobalCounter_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CounterParam)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServer).GlobalCounter(m, &echoGlobalCounterServer{stream})
}

type Echo_GlobalCounterServer interface {
	Send(*GlobalCounterResponse) error
	grpc.ServerStream
}

type echoGlobalCounterServer struct {
	grpc.ServerStream
}

func (x *echoGlobalCounterServer) Send(m *GlobalCounterResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Echo_ServiceDesc is the grpc.ServiceDesc for Echo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Echo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GlobalCounter",
			Handler:       _Echo_GlobalCounter_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/echo.proto",
}
